JuliaPluto/PlutoUI.jl

src/Builtins.jl

This PR implements displaying the current value of a slider next to it. It resolves #11.

Builtins: Show the current value of a slider next to it

---

src/Builtins.jl
src/PlutoUI.jl

Adds a radio button element. Here's the result:

Add radio buttons

---

Project.toml
src/Builtins.jl

Add a Multi-Selector (using html `select multiple`).

Add Multi-Selector

---

src/Builtins.jl

This fixes #41 
I also correct the example from the documentation for the two widgets and made PlutoUI export them.

fixed default value for DateField and TimeField

---

src/Builtins.jl

Add color picker which wraps html5 builtin input

Add color picker

---

Project.toml
assets/rangeslider.css
assets/rangeslider.js
src/PlutoUI.jl
src/RangeSlider.jl

Solution for issue #4. There are four fields: `range`, `left`, `right`, and `show_value`. I've settled on the name `RangeSlider` for the time being because I couldn't think of a better name :p Also, any feedback would be appreciated :)

Slider that displays lower and upper bound

---

src/Resource.jl

Fix #67 
I am not sure how I can test that the link works in the web version.

Fix reference in DownloadButton docstring

---

Project.toml
src/Builtins.jl

And fix some bugs along the way

Refactor builtins to use HypertextLiteral

---

Project.toml
src/Terminal.jl

Thank you for opening a Pull Request at PlutoUI.jl!
Note that your code will be _Unlicensed_ when added to PlutoUI.jl, not _MIT_ licensed like contributions to Pluto.jl. Take a look at our license: https://github.com/fonsp/PlutoUI.jl/blob/main/LICENSE
... this is ok with me.

Add show_value kwarg to with_terminal()

---

src/TableOfContents.jl

There's some noise due to using a new pluto version when editing this, would you like a more minimal change set or is it fine as is?

Fix typo in `toggle` for `indent` class.

---

src/Builtins.jl

size option for MultiSelect

---

src/TableOfContents.jl

Related to https://github.com/JuliaPluto/PlutoUI.jl/issues/97 and https://github.com/fonsp/Pluto.jl/issues/1538, PR suggested by @dralletje

Change z-index of TOC to fix cell overlapping

---

Project.toml
docs/src/index.md
src/Combine.jl
src/PlutoUI.jl
test/runtests.jl

https://htmlview.glitch.me/?https://gist.github.com/fonsp/056877529633cdbc4e91fcabdb056d3f#file-combine-jl-html

Add `combine`

---

docs/src/index.md
src/Confirm.jl
src/PlutoUI.jl
test/runtests.jl

https://user-images.githubusercontent.com/6933510/145616382-f5b01109-317d-4b21-be9c-d0229f9387cb.mov
https://htmlview.glitch.me/?https://gist.github.com/fonsp/056877529633cdbc4e91fcabdb056d3f#file-confirm-jl-html

Add `confirm`

---

.github/workflows/Test.yml
Project.toml
src/Builtins.jl
src/PlutoUI.jl
test/runtests.jl

Like `ColorStringPicker`, but it returns a `ColorTypes.Colorant` directly instead of a hex string

Add ColorTypes.jl color picker

---

src/MultiCheckBox.jl
test/runtests.jl

Allow arbitrary keys in MultiCheckBox, not just strings

---

src/Builtins.jl
test/runtests.jl

Round default slider value

---

src/Builtins.jl
test/runtests.jl

Fixes https://github.com/fonsp/Pluto.jl/issues/2002

cast NumberField values to the range type

---

src/TableOfContents.jl

Make TOC inline in print media

---

CONTRIBUTING.md

This should be fairly uncontroversial :smiley:

Fix Typos in CONTRIBUTING.md

---

src/Builtins.jl
test/runtests.jl

Updated Slider with:
- a downsampling function per #212
- a max_steps param to determine how many values should remain after downsampling
Important:

Add downsampling function to Slider

---

src/Builtins.jl
src/Clock.jl
src/Combine.jl
src/Confirm.jl
src/Layout.jl
src/MultiCheckBox.jl
src/PlutoUI.jl
src/RangeSlider.jl
src/Resource.jl
src/Scrubbable.jl
src/TableOfContents.jl
src/TerminalNotebook.jl
src/TransformedValue.jl

BEFORE
```
julia> begin 
import Pkg; 
@time Pkg.precompile(); 
@time import PlutoUI
end
Precompiling project...
1 dependency successfully precompiled in 4 seconds. 71 already precompiled.
4.558229 seconds (1.94 M allocations: 132.929 MiB, 0.39% gc time, 0.87% compilation time)
0.271933 seconds (979.17 k allocations: 63.955 MiB, 1.61% compilation time)
```
AFTER
```
julia> begin 
import Pkg; 
@time Pkg.precompile(); 
@time import PlutoUI
end
Precompiling project...
1 dependency successfully precompiled in 1 seconds. 71 already precompiled.
1.618362 seconds (1.94 M allocations: 133.126 MiB, 1.16% gc time, 2.41% compilation time)
0.126549 seconds (419.31 k allocations: 27.533 MiB, 3.40% compilation time)
```
65% improvement :)

🚀 Use "Disable in file" feature to improve loading times from 4 sec to 1.5 sec

---

Project.toml
src/Resource.jl
test/runtests.jl

https://github.com/JuliaWeb/MIMEs.jl
also add some tests

Use MIMEs.jl

---

src/TableOfContents.jl

As discussed in #238, the smooth scrolling is broken in some browsers (e.g. Chrome).
This PR just loads an external library to ensure consistent smooth scrolling across browsers.
The library seems maintained and seems to solve the problem in the issue, so it fixes #238.
Here is a video example like in #238 
https://user-images.githubusercontent.com/12846528/235166253-562a9b65-f1ce-4013-9843-aa2eeec75efe.mp4

Use an external JS library for consistent smooth scrolling

---

docs/src/index.md
src/PlutoUI.jl
src/WideCell.jl
test/runtests.jl

A new function `WideCell` to display something in an extra wide cell.
It's still responsive – if the ntoebook is too small, it will not make content wider.
https://github.com/user-attachments/assets/552175d6-2d5c-4a8b-be93-add54cf17908

WideCell to show content in an extra large cell

---

src/Builtins.jl
test/runtests.jl

Implements #302 
https://github.com/user-attachments/assets/a6327d45-506f-46ee-b18a-7b60e6345158

Make `Radio` return arbitrary values instead of `strings`
