src/Terminal.jl
Extend the `with_terminal` function to not return an html object, but a special type that also stores the result of the function. This way you can show a terminal but also inspect the result of a computation.
=> Allow getting the value from `with_terminal`

src/Terminal.jl
Hi, would be good to prevent the with_terminal() output from overflowing the screen...
Is it possible in css to set the scrollbar position to "completely down" ?
=> Restrict height of  result of with_terminal()

assets/clock.js, src/Clock.jl
* Allow to check if the clock is running
* Do bookkeeping of the number of checks
See https://github.com/fonsp/Pluto.jl/issues/476
=> Start with clock in stopped state (was ClockChecker)

src/Resource.jl
I think these are supposed to be `LocalResource` (this is the docstring for `LocalResource`), and they don't seem to work with `Resource`.
=> Use `LocalResource` in its docstring

src/TerminalNotebook.jl
Same as #150 but also adding a new cell with example `with_terminal(dump, [1,2,[3,4]])`. 
I used Pluto v0.17.0 so this comes with some other minor changes.
=> Fix #149 and add new example cell

src/Builtins.jl
Noticed when trying out https://github.com/MichaelHatherly/CommonMark.jl/issues/31.
Some of the formatting of closing `>`s for the HTML tags put them on their own lines. The commonmark spec doesn't really like this, and instead parses the dangling `>` as the start of a quote block, which leaves the preceding HTML as raw text. This is pretty reasonable for the spec to do since markdown syntax has precedence over embedded HTML. All this PR does is move those `>`s to the previous line and things work out nicely.
Another more global change could be to have `@htl` do some minifying and strip out white space characters from it's output such that the user doesn't have to care about the white space sensitivity of embedded HTML in markdown.
=> Move closing `>`s to previous lines.

src/TableOfContents.jl
Before this change, if you clicked on a heading in the TableOfContents, the page would navigate so that the selected heading was in the **centre** of the screen, which is a very behaviour and I find very difficult to adjust to. E.g. compare to how table of contents work in Wikipedia. 
Currently, when one clicks on the heading "Level 2" this is what you see. 
This makes it quite difficult for the eye to quickly locate level 2 on the screen!
With this PR, you now instead see 
which is much easier to locate, because it's quite easy for the eye to estimate where the top of the page is, but not the middle (unless you have a guide rule across your screen).
=> Make TableOfContents headers go to top of screen

src/TableOfContents.jl
Table of contents "aside" panel was (again) appearing underneath the tan cells—related to: https://github.com/fonsp/Pluto.jl/issues/1538#issuecomment-962719019
=> Re-adjusted ToC z-index

src/Builtins.jl
Clarify the docs and correct the types the `Select` and `MultiSelect` (I suspect there was some confusion in https://github.com/JuliaPluto/PlutoUI.jl/commit/18786e10f95e28a8f8cc299996291ff2a417d421 where `::String` was moved from key to value rather than being removed)
=> Doc fixes for pairs in Select/MultiSelect

src/PlutoUI.jl, src/TransformedValue.jl, test/runtests.jl
```julia
transformed_value(transform::Function, widget::Any; [initial_value::Function])
```
Create a new widget that wraps around an existing one, with a **value transformation**. 
This function creates a so-called *high-level widget*: it returns your existing widget, but with additional functionality. You can use it in your package 
A simple example to get the point accross:
```julia
function RepeatedTextSlider(text::String)	
old_widget = PlutoUI.Slider(1:10)
transform = input -> repeat(text, input)
new_widget = transformed_value(transform, old_widget)
return new_widget
end
@bind greeting RepeatedTextSlider("hello")
greeting == "hellohellohello"
```
---
This function is very useful in combination with `PlutoUI.combine`. Let's enhance our previous example by **adding a text box** where …
=> Add `transformed_value` to add a value transformation to an existing widget

src/Layout.jl
I'm adding the `style` parameter to `grid` alongside the `class` parameter to `grid`, `vbox` and `hbox`.
I have also moved the notebook editing `Pkg` activation to be hidden on top and use `Base.current_project` rather than a relative path.
=> Add class and style to other components

src/Confirm.jl
This uses `<input type=submit>` for automatic language :)
(in dutch)
The problem is now that the button says "Submit" in English, instead of "Confirm", and the function is called `confirm`... Maybe we can make an alias, called `submit`?
=> Multilingual `confirm`

src/TableOfContents.jl
There was a small problem with the CSS code for overriding the variables that change the link color attributes. In particular, `--pluto-output-h-color` was not getting overridden properly due to a few missing semicolons. All I've done in this PR is add those in, and the `:hover` behavior of ToC links now works properly.
=> Fix ToC hover styling issue

src/TableOfContents.jl
This very small change simply reduce the ToC height to only show the closed book icon when the ToC is hidden. 
This is done to minimize the vertical clutter of the ToC (now that the ToC does not remove its aside status automatically anymore) when the main text is very close to the edge of the browser.
See https://github.com/fonsp/Pluto.jl/issues/2093 for example.
New behavior example:
=> Hide ToC contents when hidden

src/Builtins.jl, test/runtests.jl
Fixes a double update when a cell defining `CounterButton` refreshes.
I also changed the tests to catch this kind of problem, but I'm not sure if that's the right fix. Pluto ignores `initial_value` if there is a `Base.get`, but the docs for `initial_value` seem to say it shouldn't. So maybe this should be fixed in Pluto instead?
=> Fix CounterButton initial value

src/TableOfContents.jl
Updates:
- The header that is currently in view is highlighted (using `IntersectionObserver`). It even works when you click-to-scroll on an item!!
- A new option `include_definitions` to include Julia variable/function definitions in the ToC
- New flat style, matching https://plutojl-preview.netlify.app/docs/
- Use `system-ui` font stack instead of Alegreya Sans
- New icons instead of emoji to match Pluto's style
- Support for HTML inside headers: images, latex, highlighting, etc
- Hover on long title names to see the complete text
- Small margin above h1 headers, creating groups of all contained subheaders
- Fix invalidation bug that caused old ToC to sometimes continue rendering in the background
- Using HypertextLiteral
https://user-images.githubusercontent.com/6933510/191618623-86e4b34 …
=> 🍭 ToC: follow scroll location & styling updates

src/WebcamInput.jl, test/runtests.jl
Make WebcamInput output a `Matrix{RGB}` instead of `Matrix{RGBA}`, because:
- I found that this is easier to work with, more common in the Julia ecosystem (e.g. DitherPunk.jl supports `RGB` images, but not `RGBA`. PlutoUI.ColorPicker gives a `RGB`) and easier to understand
- It saves 25% of data being sent over the wire
This is technically breaking, but shhhhhhhh 🤫 thats a little secret. I did not really announce WebcamInput yet, and it has only been out for a day. Many scripts that used the old code will still work, unless they accessed the `.a` attribute. I think the advantages outweigh the worries about breaking something, so I am going for it.
=> WebcamInput: RGB instead of RGBA

src/Combine.jl, src/Confirm.jl
Found as part of https://github.com/JuliaLang/julia/pull/46372 - the reference parser treats lines of uneven whitespace in a weird inconsistent way so there's some differences in whitespace in the final deindented string. This change removes those differences.
=> Fix uneven trailing whitespace in strings

src/Builtins.jl, src/MultiCheckBox.jl, test/runtests.jl
`subarrays` should take an indexable `Vector` as input, not any generator.
=> Fix `Bonds.possible_values(::MultiSelect)`

Project.toml, assets/clock.js, src/Clock.jl
https://github.com/JuliaPluto/PlutoUI.jl/assets/6933510/8cc93f34-7e62-432d-aa63-78199c3bf0b6
This will also be useful for creating short looped animations with https://github.com/JuliaPluto/PlutoSliderServer.jl/pull/29
cc @behinger
=> Clock: repeat option

src/Resource.jl, test/runtests.jl
Makes it easier to download multimedia content without converting it to a binary array yourself.
For example, something like this:
```julia
using Images
img = load(download("https://whatever"))
DownloadButton(img, "image.png")
```
Also adds a simple unit test for the download button.
=> Download button: support multimedia

src/TerminalNotebook.jl
This will remove the macro export from the TerminalNotebook as it's not defined anymore.
As it is now, you get an error with Aqua tests if you re-export PlutoUI (as it errors if you are exporting non-existing names)
=> remove `@with_terminal` export

Project.toml
Allows using Hyperscript 0.0.5. I hope it's not too much of a breaking change
=> chore: allow Hyperscript.jl 0.0.5

src/Details.jl, src/Layout.jl, src/PlutoUI.jl, test/runtests.jl
Adds new function `details` to automatically create a well formed [Details disclosure element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) (`<details>`).
Currently scoped as:
~~using PlutoUI.ExperimentalLayout: details~~
```julia
using PlutoUI #: details
```
Since this new function creates normal HTML `<details>` elements, collapsed details elements will omit their contents from any print/export. If this behavior is undesirable, it seems a JS fix could be applied as discussed [here on SO](https://stackoverflow.com/questions/19646684/force-open-the-details-summary-tag-for-print-in-chrome#answer-75260733) though I'm unsure where it would slot in.
I couldn't get `@bind` to behave properly in the Layout.jl notebook to fully test it internally. UI elements would render, …
=> Add `details`

src/Confirm.jl
Respects user agent by default, allows user to override the [submit button's value](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit#value) with the `label` kwarg.
Supersedes https://github.com/JuliaPluto/PlutoUI.jl/pull/243
=> Add optional `label` kwarg to `confirm`

src/Details.jl
Fixes: https://github.com/JuliaPluto/PlutoUI.jl/issues/295
Allows any type to be used as `summary` and leaves it up to the user to decide what is rational.
Unlike the `details` argument, `summary` is **not** embedded using `embed_display`. Instead `summary` is only wrapped by a simple `div` with appropriate CSS to provide a decent display for html-like objects.
| `summary` type | Output |
| --- | --- |
| String (unchanged) | ![image](https://github.com/JuliaPluto/PlutoUI.jl/assets/11425944/91de4aeb-f897-42aa-9df6-55f95fc0fac1) |
| `@md` | ![image](https://github.com/JuliaPluto/PlutoUI.jl/assets/11425944/865a33b0-b93c-4b47-8b8c-1ea782336203) |
| `@htl` | ![image](https://github.com/JuliaPluto/PlutoUI.jl/assets/11425944/d3b9fdd4-42a5-402e-93fb-416f1168128b) |
| other (dict) | …
=> Lift `AbstractString` type restriction on `summary` arg of `details`

src/PlutoUI.jl, src/bindname.jl
This PR makes a macro `@bindname` available when you do `using PlutoUI`.
This solves a common pattern: writing the variable name by hand in markdown, and then interpolating the `@bind` call. See e.g. https://discourse.julialang.org/t/current-maintained-interactive-julia-gui-system-mid-2024/118318/11?u=fonsp
The styling matches exactly that of a variable declaration.
This will also still work in a standalone file without Pluto:
=> New macro `@bindname` to display variable name before bond

src/Details.jl
- Follow-up from: https://github.com/JuliaPluto/PlutoUI.jl/pull/288#pullrequestreview-1880829370
=> Remove `<details>` / `<summary>` css

Project.toml
It's released for a long time. When using, I didn't find an obvious issue about the newer version.
=> Update dependence of ColorTypes.jl.
